---
VagrantConfig:
  VmBox: "hashicorp/bionic64"
  ApiVersion: "2"
  SyncedFolder: "/vagrant"
  SyncedFolderDisabled: true
VmConfig:
  - WorkerNode:
      Memory: 1024
      Cpus: 1
      LinkedClone: true   
      HostConfig: 
        - Name: Woker1
          Ip:  "192.168.56.11"
        - Name: Worker2 
          Ip:  "192.168.56.12"  
  - MasterNode: 
      Memory: 2048
      Cpus: 1
      LinkedClone: true   
      HostConfig: 
        - Name: Master1
          Ip:  "192.168.56.10"
