# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/config.yaml")

# Configure 
Vagrant.configure(configs['VagrantConfig']['ApiVersion']) do |config|
  
  # Loop through each VM configuration in VmConfig
  config.vm.box = configs['VagrantConfig']['VmBox']
  config.vm.synced_folder '.', configs['VagrantConfig']['SyncedFolder'], disabled: true
  
  # Configure Virtual Machines
  configs['VmConfig'].each_with_index do |node, index|

    node_type = node.keys.first  # Extract the VM name from the hash key

    # Virtual Machine Definintions 
    boxes = []

    node[node_type]['HostConfig'].each do |item|
      boxes << { name: item['Name'], ip: item['Ip'] }
    end

    # Virtual Machine Hardware Configuration
    config.vm.provider :virtualbox do |v|
      v.memory = node[node_type]['Memory']
      v.cpus = node[node_type]['Cpus']
      v.linked_clone = node[node_type]['LinkedClone']
      #v.name = "#{index + 1}_#{boxes["Name"]}"
    end 

    boxes.each do |opts|

      config.vm.define opts[:name] do |c|
        config.vm.hostname = opts[:name]
        config.vm.network :private_network, ip: opts[:ip]
      end
    
    end
  end
end